"""
path_follower.py

Makes Ved follow a path generated by Path Planner.

Author: NeuraOS
"""

import math


class PathFollower:

    def __init__(self):

        self.path = []
        self.current_index = 0
        self.goal_tolerance = 0.30

    # ---------------------------------
    # Load Path
    # ---------------------------------

    def set_path(self, path):

        self.path = path
        self.current_index = 0

    # ---------------------------------
    # Finished?
    # ---------------------------------

    def finished(self):

        return self.current_index >= len(self.path)

    # ---------------------------------
    # Current Target
    # ---------------------------------

    def current_target(self):

        if self.finished():
            return None

        return self.path[self.current_index]

    # ---------------------------------
    # Update
    # ---------------------------------

    def update(self, pose):

        if self.finished():

            return {

                "command": "STOP"

            }

        target = self.current_target()
        print("Pose:", pose)
        print("Target:", target)

        dx = target["x"] - pose["x"]
        dy = target["y"] - pose["y"]

        distance = math.sqrt(dx**2 + dy**2)

        if distance < self.goal_tolerance:

            self.current_index += 1

            return {

                "command": "WAYPOINT_REACHED"

            }

        desired_heading = math.degrees(

            math.atan2(dy, dx)

        )

        heading_error = desired_heading - pose["heading"]

        while heading_error > 180:
            heading_error -= 360

        while heading_error < -180:
            heading_error += 360

        if abs(heading_error) > 15:

            if heading_error > 0:

                return {

                    "command": "TURN_LEFT",

                    "angle": heading_error

                }

            else:

                return {

                    "command": "TURN_RIGHT",

                    "angle": abs(heading_error)

                }

        return {

            "command": "FORWARD",

            "distance": distance

        }


pathFollower = PathFollower()