[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    livetronic/ESP32Servo @ ^3.0.6
    adafruit/Adafruit VL53L0X @ ^1.2.4
    microflo/NewPing @ ^1.9.7